### PR TITLE
Throw on invalid input

### LINKED ISSUE #1: Throw an error if a task not a function
I've seen on several occasions that devs were accidentally passing promises to `p-series` instead of functions that return promises. Sometimes I did this error myself and then I was wondering why the application doesn't work as it should.

Do you think it would be OK to add validation of the task. If the task is not a function, and error should be thrown.

### PR DESCRIPTION
**Pull request by kevva**
Had to iterate through the input before the call to `pReduce` since it returns the resolved values and not the inputted ones.

Also used `is` here so we get a better error message if the task is a `Promise` for instance.

Fixes #1.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -1,8 +1,18 @@
...
 const pReduce = require('p-reduce');
+const is = require('@sindresorhus/is');
 
 module.exports = iterable => {
 	const ret = [];
+
+	for (const task of iterable) {
+		const type = is(task);
+
+		if (type !== 'Function') {
```
Comment (sindresorhus) [inline index.js:11]: We don't really need all of `is` for this. `typeof task !== 'function'` should be good enough.

Comment (kevva) [reply index.js:11]: Yeah, but a common mistake is to supply a `Promise` instead of a `function`. If we just do `typeof` it'll log it as `object` which isn't super clear.

Guess it's not super important though, as long as we error.

Comment (sindresorhus) [reply index.js:11]: I see. Ok, leave it. We'll switch to `ow` soon enough anyway.
